//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Data;
using System.Data.Common;
using Dos.ORM;
using Dos.ORM.Common;

namespace SolarhotwaterprojectModel
{

	/// <summary>
	/// 实体类系统采集器 。(属性说明自动提取数据库字段的描述信息)
	/// </summary>
	[Table("系统采集器")]
	[Serializable]
	public partial class 系统采集器 : Entity 
	{
		#region Model
		private string _TimeStamp;
		private string _Num01;
		private string _Num02;
		private string _Num03;
		private string _Num04;
		private string _Num05;
		private string _Num06;
		private string _Num07;
		private string _Num08;
		private string _Num09;
		private string _Num10;
		private string _Num11;
		private string _Num12;
		private string _Num13;
		private string _Num14;
		private string _Num15;
		private string _Num16;
		private string _Num17;
		private string _Num18;
		private string _Num19;
		private string _Num20;
		private string _Num21;
		private string _Num22;
		/// <summary>
		/// 
		/// </summary>
		public string TimeStamp
		{
			get{ return _TimeStamp; }
			set
			{
				this.OnPropertyValueChange(_.TimeStamp,_TimeStamp,value);
				this._TimeStamp=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Num01
		{
			get{ return _Num01; }
			set
			{
				this.OnPropertyValueChange(_.Num01,_Num01,value);
				this._Num01=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Num02
		{
			get{ return _Num02; }
			set
			{
				this.OnPropertyValueChange(_.Num02,_Num02,value);
				this._Num02=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Num03
		{
			get{ return _Num03; }
			set
			{
				this.OnPropertyValueChange(_.Num03,_Num03,value);
				this._Num03=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Num04
		{
			get{ return _Num04; }
			set
			{
				this.OnPropertyValueChange(_.Num04,_Num04,value);
				this._Num04=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Num05
		{
			get{ return _Num05; }
			set
			{
				this.OnPropertyValueChange(_.Num05,_Num05,value);
				this._Num05=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Num06
		{
			get{ return _Num06; }
			set
			{
				this.OnPropertyValueChange(_.Num06,_Num06,value);
				this._Num06=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Num07
		{
			get{ return _Num07; }
			set
			{
				this.OnPropertyValueChange(_.Num07,_Num07,value);
				this._Num07=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Num08
		{
			get{ return _Num08; }
			set
			{
				this.OnPropertyValueChange(_.Num08,_Num08,value);
				this._Num08=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Num09
		{
			get{ return _Num09; }
			set
			{
				this.OnPropertyValueChange(_.Num09,_Num09,value);
				this._Num09=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Num10
		{
			get{ return _Num10; }
			set
			{
				this.OnPropertyValueChange(_.Num10,_Num10,value);
				this._Num10=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Num11
		{
			get{ return _Num11; }
			set
			{
				this.OnPropertyValueChange(_.Num11,_Num11,value);
				this._Num11=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Num12
		{
			get{ return _Num12; }
			set
			{
				this.OnPropertyValueChange(_.Num12,_Num12,value);
				this._Num12=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Num13
		{
			get{ return _Num13; }
			set
			{
				this.OnPropertyValueChange(_.Num13,_Num13,value);
				this._Num13=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Num14
		{
			get{ return _Num14; }
			set
			{
				this.OnPropertyValueChange(_.Num14,_Num14,value);
				this._Num14=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Num15
		{
			get{ return _Num15; }
			set
			{
				this.OnPropertyValueChange(_.Num15,_Num15,value);
				this._Num15=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Num16
		{
			get{ return _Num16; }
			set
			{
				this.OnPropertyValueChange(_.Num16,_Num16,value);
				this._Num16=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Num17
		{
			get{ return _Num17; }
			set
			{
				this.OnPropertyValueChange(_.Num17,_Num17,value);
				this._Num17=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Num18
		{
			get{ return _Num18; }
			set
			{
				this.OnPropertyValueChange(_.Num18,_Num18,value);
				this._Num18=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Num19
		{
			get{ return _Num19; }
			set
			{
				this.OnPropertyValueChange(_.Num19,_Num19,value);
				this._Num19=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Num20
		{
			get{ return _Num20; }
			set
			{
				this.OnPropertyValueChange(_.Num20,_Num20,value);
				this._Num20=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Num21
		{
			get{ return _Num21; }
			set
			{
				this.OnPropertyValueChange(_.Num21,_Num21,value);
				this._Num21=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Num22
		{
			get{ return _Num22; }
			set
			{
				this.OnPropertyValueChange(_.Num22,_Num22,value);
				this._Num22=value;
			}
		}
		#endregion

		#region Method
		/// <summary>
		/// 获取列信息
		/// </summary>
		public override Field[] GetFields()
		{
			return new Field[] {
				_.TimeStamp,
				_.Num01,
				_.Num02,
				_.Num03,
				_.Num04,
				_.Num05,
				_.Num06,
				_.Num07,
				_.Num08,
				_.Num09,
				_.Num10,
				_.Num11,
				_.Num12,
				_.Num13,
				_.Num14,
				_.Num15,
				_.Num16,
				_.Num17,
				_.Num18,
				_.Num19,
				_.Num20,
				_.Num21,
				_.Num22};
		}
		/// <summary>
		/// 获取值信息
		/// </summary>
		public override object[] GetValues()
		{
			return new object[] {
				this._TimeStamp,
				this._Num01,
				this._Num02,
				this._Num03,
				this._Num04,
				this._Num05,
				this._Num06,
				this._Num07,
				this._Num08,
				this._Num09,
				this._Num10,
				this._Num11,
				this._Num12,
				this._Num13,
				this._Num14,
				this._Num15,
				this._Num16,
				this._Num17,
				this._Num18,
				this._Num19,
				this._Num20,
				this._Num21,
				this._Num22};
		}
		#endregion

		#region _Field
		/// <summary>
		/// 字段信息
		/// </summary>
		public class _
		{
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*","系统采集器");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field TimeStamp = new Field("TimeStamp","系统采集器","TimeStamp");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Num01 = new Field("Num01","系统采集器","Num01");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Num02 = new Field("Num02","系统采集器","Num02");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Num03 = new Field("Num03","系统采集器","Num03");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Num04 = new Field("Num04","系统采集器","Num04");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Num05 = new Field("Num05","系统采集器","Num05");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Num06 = new Field("Num06","系统采集器","Num06");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Num07 = new Field("Num07","系统采集器","Num07");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Num08 = new Field("Num08","系统采集器","Num08");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Num09 = new Field("Num09","系统采集器","Num09");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Num10 = new Field("Num10","系统采集器","Num10");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Num11 = new Field("Num11","系统采集器","Num11");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Num12 = new Field("Num12","系统采集器","Num12");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Num13 = new Field("Num13","系统采集器","Num13");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Num14 = new Field("Num14","系统采集器","Num14");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Num15 = new Field("Num15","系统采集器","Num15");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Num16 = new Field("Num16","系统采集器","Num16");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Num17 = new Field("Num17","系统采集器","Num17");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Num18 = new Field("Num18","系统采集器","Num18");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Num19 = new Field("Num19","系统采集器","Num19");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Num20 = new Field("Num20","系统采集器","Num20");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Num21 = new Field("Num21","系统采集器","Num21");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Num22 = new Field("Num22","系统采集器","Num22");
		}
		#endregion


	}
}

