//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Data;
using System.Data.Common;
using Dos.ORM;
using Dos.ORM.Common;

namespace SolarhotwaterprojectModel
{

	/// <summary>
	/// 实体类AreaInfo 。(属性说明自动提取数据库字段的描述信息)
	/// </summary>
	[Table("AreaInfo")]
	[Serializable]
	public partial class AreaInfo : Entity 
	{
		#region Model
		private string _Province;
		private string _City;
		private string _Code;
		/// <summary>
		/// 
		/// </summary>
		public string Province
		{
			get{ return _Province; }
			set
			{
				this.OnPropertyValueChange(_.Province,_Province,value);
				this._Province=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string City
		{
			get{ return _City; }
			set
			{
				this.OnPropertyValueChange(_.City,_City,value);
				this._City=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Code
		{
			get{ return _Code; }
			set
			{
				this.OnPropertyValueChange(_.Code,_Code,value);
				this._Code=value;
			}
		}
		#endregion

		#region Method
		/// <summary>
		/// 获取实体中的主键列
		/// </summary>
		public override Field[] GetPrimaryKeyFields()
		{
			return new Field[] {
				_.City};
		}
		/// <summary>
		/// 获取列信息
		/// </summary>
		public override Field[] GetFields()
		{
			return new Field[] {
				_.Province,
				_.City,
				_.Code};
		}
		/// <summary>
		/// 获取值信息
		/// </summary>
		public override object[] GetValues()
		{
			return new object[] {
				this._Province,
				this._City,
				this._Code};
		}
		#endregion

		#region _Field
		/// <summary>
		/// 字段信息
		/// </summary>
		public class _
		{
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*","AreaInfo");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Province = new Field("Province","AreaInfo","Province");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field City = new Field("City","AreaInfo","City");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Code = new Field("Code","AreaInfo","Code");
		}
		#endregion


	}
}

