//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Data;
using System.Data.Common;
using Dos.ORM;
using Dos.ORM.Common;

namespace SolarhotwaterprojectModel
{

	/// <summary>
	/// 实体类CollectorInfo 。(属性说明自动提取数据库字段的描述信息)
	/// </summary>
	[Table("CollectorInfo")]
	[Serializable]
	public partial class CollectorInfo : Entity 
	{
		#region Model
		private string _AreaName;
		private string _ProjectName;
		private string _CollectorName;
		private string _CollectorCode;
		private string _CollectorMode;
		private string _CollectPointNum;
		private string _UserID;
		private string _UserPassword;
		/// <summary>
		/// 
		/// </summary>
		public string AreaName
		{
			get{ return _AreaName; }
			set
			{
				this.OnPropertyValueChange(_.AreaName,_AreaName,value);
				this._AreaName=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string ProjectName
		{
			get{ return _ProjectName; }
			set
			{
				this.OnPropertyValueChange(_.ProjectName,_ProjectName,value);
				this._ProjectName=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string CollectorName
		{
			get{ return _CollectorName; }
			set
			{
				this.OnPropertyValueChange(_.CollectorName,_CollectorName,value);
				this._CollectorName=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string CollectorCode
		{
			get{ return _CollectorCode; }
			set
			{
				this.OnPropertyValueChange(_.CollectorCode,_CollectorCode,value);
				this._CollectorCode=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string CollectorMode
		{
			get{ return _CollectorMode; }
			set
			{
				this.OnPropertyValueChange(_.CollectorMode,_CollectorMode,value);
				this._CollectorMode=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string CollectPointNum
		{
			get{ return _CollectPointNum; }
			set
			{
				this.OnPropertyValueChange(_.CollectPointNum,_CollectPointNum,value);
				this._CollectPointNum=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string UserID
		{
			get{ return _UserID; }
			set
			{
				this.OnPropertyValueChange(_.UserID,_UserID,value);
				this._UserID=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string UserPassword
		{
			get{ return _UserPassword; }
			set
			{
				this.OnPropertyValueChange(_.UserPassword,_UserPassword,value);
				this._UserPassword=value;
			}
		}
		#endregion

		#region Method
		/// <summary>
		/// 获取列信息
		/// </summary>
		public override Field[] GetFields()
		{
			return new Field[] {
				_.AreaName,
				_.ProjectName,
				_.CollectorName,
				_.CollectorCode,
				_.CollectorMode,
				_.CollectPointNum,
				_.UserID,
				_.UserPassword};
		}
		/// <summary>
		/// 获取值信息
		/// </summary>
		public override object[] GetValues()
		{
			return new object[] {
				this._AreaName,
				this._ProjectName,
				this._CollectorName,
				this._CollectorCode,
				this._CollectorMode,
				this._CollectPointNum,
				this._UserID,
				this._UserPassword};
		}
		#endregion

		#region _Field
		/// <summary>
		/// 字段信息
		/// </summary>
		public class _
		{
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*","CollectorInfo");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field AreaName = new Field("AreaName","CollectorInfo","AreaName");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field ProjectName = new Field("ProjectName","CollectorInfo","ProjectName");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field CollectorName = new Field("CollectorName","CollectorInfo","CollectorName");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field CollectorCode = new Field("CollectorCode","CollectorInfo","CollectorCode");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field CollectorMode = new Field("CollectorMode","CollectorInfo","CollectorMode");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field CollectPointNum = new Field("CollectPointNum","CollectorInfo","CollectPointNum");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field UserID = new Field("UserID","CollectorInfo","UserID");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field UserPassword = new Field("UserPassword","CollectorInfo","UserPassword");
		}
		#endregion


	}
}

