//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Data;
using System.Data.Common;
using Dos.ORM;
using Dos.ORM.Common;

namespace SolarhotwaterprojectModel
{

	/// <summary>
	/// 实体类CompanyInfo 。(属性说明自动提取数据库字段的描述信息)
	/// </summary>
	[Table("CompanyInfo")]
	[Serializable]
	public partial class CompanyInfo : Entity 
	{
		#region Model
		private string _CompanyName;
		private string _CompanyLogin;
		private string _CompanyPsw;
		/// <summary>
		/// 
		/// </summary>
		public string CompanyName
		{
			get{ return _CompanyName; }
			set
			{
				this.OnPropertyValueChange(_.CompanyName,_CompanyName,value);
				this._CompanyName=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string CompanyLogin
		{
			get{ return _CompanyLogin; }
			set
			{
				this.OnPropertyValueChange(_.CompanyLogin,_CompanyLogin,value);
				this._CompanyLogin=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string CompanyPsw
		{
			get{ return _CompanyPsw; }
			set
			{
				this.OnPropertyValueChange(_.CompanyPsw,_CompanyPsw,value);
				this._CompanyPsw=value;
			}
		}
		#endregion

		#region Method
		/// <summary>
		/// 获取列信息
		/// </summary>
		public override Field[] GetFields()
		{
			return new Field[] {
				_.CompanyName,
				_.CompanyLogin,
				_.CompanyPsw};
		}
		/// <summary>
		/// 获取值信息
		/// </summary>
		public override object[] GetValues()
		{
			return new object[] {
				this._CompanyName,
				this._CompanyLogin,
				this._CompanyPsw};
		}
		#endregion

		#region _Field
		/// <summary>
		/// 字段信息
		/// </summary>
		public class _
		{
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*","CompanyInfo");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field CompanyName = new Field("CompanyName","CompanyInfo","CompanyName");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field CompanyLogin = new Field("CompanyLogin","CompanyInfo","CompanyLogin");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field CompanyPsw = new Field("CompanyPsw","CompanyInfo","CompanyPsw");
		}
		#endregion


	}
}

