//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Data;
using System.Data.Common;
using Dos.ORM;
using Dos.ORM.Common;

namespace SolarhotwaterprojectModel
{

	/// <summary>
	/// 实体类ProjectInfo 。(属性说明自动提取数据库字段的描述信息)
	/// </summary>
	[Table("ProjectInfo")]
	[Serializable]
	public partial class ProjectInfo : Entity 
	{
		#region Model
		private string _AreaName;
		private string _AreaCode;
		private string _ProjectName;
		private string _ProjectCode;
		private string _TecType;
		private string _TecCode;
		private string _UserID;
		private string _UserPassword;
		/// <summary>
		/// 
		/// </summary>
		public string AreaName
		{
			get{ return _AreaName; }
			set
			{
				this.OnPropertyValueChange(_.AreaName,_AreaName,value);
				this._AreaName=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string AreaCode
		{
			get{ return _AreaCode; }
			set
			{
				this.OnPropertyValueChange(_.AreaCode,_AreaCode,value);
				this._AreaCode=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string ProjectName
		{
			get{ return _ProjectName; }
			set
			{
				this.OnPropertyValueChange(_.ProjectName,_ProjectName,value);
				this._ProjectName=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string ProjectCode
		{
			get{ return _ProjectCode; }
			set
			{
				this.OnPropertyValueChange(_.ProjectCode,_ProjectCode,value);
				this._ProjectCode=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string TecType
		{
			get{ return _TecType; }
			set
			{
				this.OnPropertyValueChange(_.TecType,_TecType,value);
				this._TecType=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string TecCode
		{
			get{ return _TecCode; }
			set
			{
				this.OnPropertyValueChange(_.TecCode,_TecCode,value);
				this._TecCode=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string UserID
		{
			get{ return _UserID; }
			set
			{
				this.OnPropertyValueChange(_.UserID,_UserID,value);
				this._UserID=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string UserPassword
		{
			get{ return _UserPassword; }
			set
			{
				this.OnPropertyValueChange(_.UserPassword,_UserPassword,value);
				this._UserPassword=value;
			}
		}
		#endregion

		#region Method
		/// <summary>
		/// 获取实体中的主键列
		/// </summary>
		public override Field[] GetPrimaryKeyFields()
		{
			return new Field[] {
				_.ProjectName};
		}
		/// <summary>
		/// 获取列信息
		/// </summary>
		public override Field[] GetFields()
		{
			return new Field[] {
				_.AreaName,
				_.AreaCode,
				_.ProjectName,
				_.ProjectCode,
				_.TecType,
				_.TecCode,
				_.UserID,
				_.UserPassword};
		}
		/// <summary>
		/// 获取值信息
		/// </summary>
		public override object[] GetValues()
		{
			return new object[] {
				this._AreaName,
				this._AreaCode,
				this._ProjectName,
				this._ProjectCode,
				this._TecType,
				this._TecCode,
				this._UserID,
				this._UserPassword};
		}
		#endregion

		#region _Field
		/// <summary>
		/// 字段信息
		/// </summary>
		public class _
		{
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*","ProjectInfo");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field AreaName = new Field("AreaName","ProjectInfo","AreaName");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field AreaCode = new Field("AreaCode","ProjectInfo","AreaCode");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field ProjectName = new Field("ProjectName","ProjectInfo","ProjectName");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field ProjectCode = new Field("ProjectCode","ProjectInfo","ProjectCode");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field TecType = new Field("TecType","ProjectInfo","TecType");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field TecCode = new Field("TecCode","ProjectInfo","TecCode");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field UserID = new Field("UserID","ProjectInfo","UserID");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field UserPassword = new Field("UserPassword","ProjectInfo","UserPassword");
		}
		#endregion


	}
}

