//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Data;
using System.Data.Common;
using Dos.ORM;
using Dos.ORM.Common;

namespace SolarhotwaterprojectModel
{

	/// <summary>
	/// 实体类tb_Alarm 。(属性说明自动提取数据库字段的描述信息)
	/// </summary>
	[Table("tb_Alarm")]
	[Serializable]
	public partial class tb_Alarm : Entity 
	{
		#region Model
		private int _ID;
		private DateTime? _TimeStamp;
		private string _AreaName;
		private string _ProjectName;
		private string _CollectorName;
		private string _Info;
		private string _State;
		/// <summary>
		/// 
		/// </summary>
		public int ID
		{
			get{ return _ID; }
			set
			{
				this.OnPropertyValueChange(_.ID,_ID,value);
				this._ID=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public DateTime? TimeStamp
		{
			get{ return _TimeStamp; }
			set
			{
				this.OnPropertyValueChange(_.TimeStamp,_TimeStamp,value);
				this._TimeStamp=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string AreaName
		{
			get{ return _AreaName; }
			set
			{
				this.OnPropertyValueChange(_.AreaName,_AreaName,value);
				this._AreaName=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string ProjectName
		{
			get{ return _ProjectName; }
			set
			{
				this.OnPropertyValueChange(_.ProjectName,_ProjectName,value);
				this._ProjectName=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string CollectorName
		{
			get{ return _CollectorName; }
			set
			{
				this.OnPropertyValueChange(_.CollectorName,_CollectorName,value);
				this._CollectorName=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Info
		{
			get{ return _Info; }
			set
			{
				this.OnPropertyValueChange(_.Info,_Info,value);
				this._Info=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string State
		{
			get{ return _State; }
			set
			{
				this.OnPropertyValueChange(_.State,_State,value);
				this._State=value;
			}
		}
		#endregion

		#region Method
		/// <summary>
		/// 获取实体中的标识列
		/// </summary>
		public override Field GetIdentityField()
		{
			return _.ID;
		}
		/// <summary>
		/// 获取列信息
		/// </summary>
		public override Field[] GetFields()
		{
			return new Field[] {
				_.ID,
				_.TimeStamp,
				_.AreaName,
				_.ProjectName,
				_.CollectorName,
				_.Info,
				_.State};
		}
		/// <summary>
		/// 获取值信息
		/// </summary>
		public override object[] GetValues()
		{
			return new object[] {
				this._ID,
				this._TimeStamp,
				this._AreaName,
				this._ProjectName,
				this._CollectorName,
				this._Info,
				this._State};
		}
		#endregion

		#region _Field
		/// <summary>
		/// 字段信息
		/// </summary>
		public class _
		{
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*","tb_Alarm");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field ID = new Field("ID","tb_Alarm","ID");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field TimeStamp = new Field("TimeStamp","tb_Alarm","TimeStamp");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field AreaName = new Field("AreaName","tb_Alarm","AreaName");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field ProjectName = new Field("ProjectName","tb_Alarm","ProjectName");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field CollectorName = new Field("CollectorName","tb_Alarm","CollectorName");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Info = new Field("Info","tb_Alarm","Info");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field State = new Field("State","tb_Alarm","State");
		}
		#endregion


	}
}

