//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Data;
using System.Data.Common;
using Dos.ORM;
using Dos.ORM.Common;

namespace SolarhotwaterprojectModel
{

	/// <summary>
	/// 实体类VW_LastIndex 。(属性说明自动提取数据库字段的描述信息)
	/// </summary>
	[Table("VW_LastIndex")]
	[Serializable]
	public partial class VW_LastIndex : Entity 
	{
		#region Model
		private DateTime? _TimeStamp;
		private float? _Allc;
		private float? _AllEsys;
		private float? _AllEhp;
		private float? _AllQc;
		private float? _AllQhp;
		private float? _AllQsh;
		private float? _AllQss;
		/// <summary>
		/// 
		/// </summary>
		public DateTime? TimeStamp
		{
			get{ return _TimeStamp; }
			set
			{
				this.OnPropertyValueChange(_.TimeStamp,_TimeStamp,value);
				this._TimeStamp=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public float? Allc
		{
			get{ return _Allc; }
			set
			{
				this.OnPropertyValueChange(_.Allc,_Allc,value);
				this._Allc=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public float? AllEsys
		{
			get{ return _AllEsys; }
			set
			{
				this.OnPropertyValueChange(_.AllEsys,_AllEsys,value);
				this._AllEsys=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public float? AllEhp
		{
			get{ return _AllEhp; }
			set
			{
				this.OnPropertyValueChange(_.AllEhp,_AllEhp,value);
				this._AllEhp=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public float? AllQc
		{
			get{ return _AllQc; }
			set
			{
				this.OnPropertyValueChange(_.AllQc,_AllQc,value);
				this._AllQc=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public float? AllQhp
		{
			get{ return _AllQhp; }
			set
			{
				this.OnPropertyValueChange(_.AllQhp,_AllQhp,value);
				this._AllQhp=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public float? AllQsh
		{
			get{ return _AllQsh; }
			set
			{
				this.OnPropertyValueChange(_.AllQsh,_AllQsh,value);
				this._AllQsh=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public float? AllQss
		{
			get{ return _AllQss; }
			set
			{
				this.OnPropertyValueChange(_.AllQss,_AllQss,value);
				this._AllQss=value;
			}
		}
		#endregion

		#region Method
		/// <summary>
		/// 是否只读
		/// </summary>
		public override bool IsReadOnly()
		{
			return true;
		}
		/// <summary>
		/// 获取列信息
		/// </summary>
		public override Field[] GetFields()
		{
			return new Field[] {
				_.TimeStamp,
				_.Allc,
				_.AllEsys,
				_.AllEhp,
				_.AllQc,
				_.AllQhp,
				_.AllQsh,
				_.AllQss};
		}
		/// <summary>
		/// 获取值信息
		/// </summary>
		public override object[] GetValues()
		{
			return new object[] {
				this._TimeStamp,
				this._Allc,
				this._AllEsys,
				this._AllEhp,
				this._AllQc,
				this._AllQhp,
				this._AllQsh,
				this._AllQss};
		}
		#endregion

		#region _Field
		/// <summary>
		/// 字段信息
		/// </summary>
		public class _
		{
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*","VW_LastIndex");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field TimeStamp = new Field("TimeStamp","VW_LastIndex","TimeStamp");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Allc = new Field("Allc","VW_LastIndex","Allc");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field AllEsys = new Field("AllEsys","VW_LastIndex","AllEsys");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field AllEhp = new Field("AllEhp","VW_LastIndex","AllEhp");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field AllQc = new Field("AllQc","VW_LastIndex","AllQc");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field AllQhp = new Field("AllQhp","VW_LastIndex","AllQhp");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field AllQsh = new Field("AllQsh","VW_LastIndex","AllQsh");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field AllQss = new Field("AllQss","VW_LastIndex","AllQss");
		}
		#endregion


	}
}

