//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Data;
using System.Data.Common;
using Dos.ORM;
using Dos.ORM.Common;

namespace SolarhotwaterprojectModel
{

	/// <summary>
	/// 实体类VW_Monitoringindex 。(属性说明自动提取数据库字段的描述信息)
	/// </summary>
	[Table("VW_Monitoringindex")]
	[Serializable]
	public partial class VW_Monitoringindex : Entity 
	{
		#region Model
		private string _CollectPointName;
		private int? _CollectPointCode;
		/// <summary>
		/// 
		/// </summary>
		public string CollectPointName
		{
			get{ return _CollectPointName; }
			set
			{
				this.OnPropertyValueChange(_.CollectPointName,_CollectPointName,value);
				this._CollectPointName=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? CollectPointCode
		{
			get{ return _CollectPointCode; }
			set
			{
				this.OnPropertyValueChange(_.CollectPointCode,_CollectPointCode,value);
				this._CollectPointCode=value;
			}
		}
		#endregion

		#region Method
		/// <summary>
		/// 是否只读
		/// </summary>
		public override bool IsReadOnly()
		{
			return true;
		}
		/// <summary>
		/// 获取列信息
		/// </summary>
		public override Field[] GetFields()
		{
			return new Field[] {
				_.CollectPointName,
				_.CollectPointCode};
		}
		/// <summary>
		/// 获取值信息
		/// </summary>
		public override object[] GetValues()
		{
			return new object[] {
				this._CollectPointName,
				this._CollectPointCode};
		}
		#endregion

		#region _Field
		/// <summary>
		/// 字段信息
		/// </summary>
		public class _
		{
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*","VW_Monitoringindex");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field CollectPointName = new Field("CollectPointName","VW_Monitoringindex","CollectPointName");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field CollectPointCode = new Field("CollectPointCode","VW_Monitoringindex","CollectPointCode");
		}
		#endregion


	}
}

