//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Data;
using System.Data.Common;
using Dos.ORM;
using Dos.ORM.Common;

namespace SolarhotwaterprojectModel
{

	/// <summary>
	/// 实体类VW_TodayEmissionreduction 。(属性说明自动提取数据库字段的描述信息)
	/// </summary>
	[Table("VW_TodayEmissionreduction")]
	[Serializable]
	public partial class VW_TodayEmissionreduction : Entity 
	{
		#region Model
		private DateTime? _TimeStamp;
		private float? _AllQuse;
		private float? _AllQss;
		private float? _Allmco2;
		private float? _Allmso2;
		private float? _Allmnox;
		private float? _Allmfc;
		/// <summary>
		/// 
		/// </summary>
		public DateTime? TimeStamp
		{
			get{ return _TimeStamp; }
			set
			{
				this.OnPropertyValueChange(_.TimeStamp,_TimeStamp,value);
				this._TimeStamp=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public float? AllQuse
		{
			get{ return _AllQuse; }
			set
			{
				this.OnPropertyValueChange(_.AllQuse,_AllQuse,value);
				this._AllQuse=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public float? AllQss
		{
			get{ return _AllQss; }
			set
			{
				this.OnPropertyValueChange(_.AllQss,_AllQss,value);
				this._AllQss=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public float? Allmco2
		{
			get{ return _Allmco2; }
			set
			{
				this.OnPropertyValueChange(_.Allmco2,_Allmco2,value);
				this._Allmco2=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public float? Allmso2
		{
			get{ return _Allmso2; }
			set
			{
				this.OnPropertyValueChange(_.Allmso2,_Allmso2,value);
				this._Allmso2=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public float? Allmnox
		{
			get{ return _Allmnox; }
			set
			{
				this.OnPropertyValueChange(_.Allmnox,_Allmnox,value);
				this._Allmnox=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public float? Allmfc
		{
			get{ return _Allmfc; }
			set
			{
				this.OnPropertyValueChange(_.Allmfc,_Allmfc,value);
				this._Allmfc=value;
			}
		}
		#endregion

		#region Method
		/// <summary>
		/// 是否只读
		/// </summary>
		public override bool IsReadOnly()
		{
			return true;
		}
		/// <summary>
		/// 获取列信息
		/// </summary>
		public override Field[] GetFields()
		{
			return new Field[] {
				_.TimeStamp,
				_.AllQuse,
				_.AllQss,
				_.Allmco2,
				_.Allmso2,
				_.Allmnox,
				_.Allmfc};
		}
		/// <summary>
		/// 获取值信息
		/// </summary>
		public override object[] GetValues()
		{
			return new object[] {
				this._TimeStamp,
				this._AllQuse,
				this._AllQss,
				this._Allmco2,
				this._Allmso2,
				this._Allmnox,
				this._Allmfc};
		}
		#endregion

		#region _Field
		/// <summary>
		/// 字段信息
		/// </summary>
		public class _
		{
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*","VW_TodayEmissionreduction");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field TimeStamp = new Field("TimeStamp","VW_TodayEmissionreduction","TimeStamp");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field AllQuse = new Field("AllQuse","VW_TodayEmissionreduction","AllQuse");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field AllQss = new Field("AllQss","VW_TodayEmissionreduction","AllQss");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Allmco2 = new Field("Allmco2","VW_TodayEmissionreduction","Allmco2");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Allmso2 = new Field("Allmso2","VW_TodayEmissionreduction","Allmso2");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Allmnox = new Field("Allmnox","VW_TodayEmissionreduction","Allmnox");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Allmfc = new Field("Allmfc","VW_TodayEmissionreduction","Allmfc");
		}
		#endregion


	}
}

