//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dos.ORM;

namespace SolarhotwaterprojectModel
{
    /// <summary>
    /// 实体类系统采集器参数。(属性说明自动提取数据库字段的描述信息)
    /// </summary>
    [Table("系统采集器参数")]
    [Serializable]
    public partial class 系统采集器参数 : Entity
    {
        #region Model
        private string _TimeStamp;
        private string _设定温度;
        private string _水泵频率P;
        private string _水泵频率I;
        private string _水泵频率D;
        private string _进水电磁阀开关;
        private string _出水电磁阀开关;
        private string _市电光伏开关;
        private string _控制柜手动开关;

        /// <summary>
        /// 
        /// </summary>
        [Field("TimeStamp")]
        public string TimeStamp
        {
            get { return _TimeStamp; }
            set
            {
                this.OnPropertyValueChange("TimeStamp");
                this._TimeStamp = value;
            }
        }

        private void OnPropertyValueChange(string v)
        {
            throw new NotImplementedException();
        }

        /// <summary>
        /// 
        /// </summary>
        [Field("设定温度")]
        public string 设定温度
        {
            get { return _设定温度; }
            set
            {
                this.OnPropertyValueChange("设定温度");
                this._设定温度 = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("水泵频率P")]
        public string 水泵频率P
        {
            get { return _水泵频率P; }
            set
            {
                this.OnPropertyValueChange("水泵频率P");
                this._水泵频率P = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("水泵频率I")]
        public string 水泵频率I
        {
            get { return _水泵频率I; }
            set
            {
                this.OnPropertyValueChange("水泵频率I");
                this._水泵频率I = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("水泵频率D")]
        public string 水泵频率D
        {
            get { return _水泵频率D; }
            set
            {
                this.OnPropertyValueChange("水泵频率D");
                this._水泵频率D = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("进水电磁阀开关")]
        public string 进水电磁阀开关
        {
            get { return _进水电磁阀开关; }
            set
            {
                this.OnPropertyValueChange("进水电磁阀开关");
                this._进水电磁阀开关 = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("出水电磁阀开关")]
        public string 出水电磁阀开关
        {
            get { return _出水电磁阀开关; }
            set
            {
                this.OnPropertyValueChange("出水电磁阀开关");
                this._出水电磁阀开关 = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("市电光伏开关")]
        public string 市电光伏开关
        {
            get { return _市电光伏开关; }
            set
            {
                this.OnPropertyValueChange("市电光伏开关");
                this._市电光伏开关 = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("控制柜手动开关")]
        public string 控制柜手动开关
        {
            get { return _控制柜手动开关; }
            set
            {
                this.OnPropertyValueChange("控制柜手动开关");
                this._控制柜手动开关 = value;
            }
        }
        #endregion

        #region Method
        /// <summary>
        /// 获取实体中的主键列
        /// </summary>
        public override Field[] GetPrimaryKeyFields()
        {
            return new Field[] {
            };
        }
        /// <summary>
        /// 获取列信息
        /// </summary>
        public override Field[] GetFields()
        {
            return new Field[] {
                _.TimeStamp,
                _.设定温度,
                _.水泵频率P,
                _.水泵频率I,
                _.水泵频率D,
                _.进水电磁阀开关,
                _.出水电磁阀开关,
                _.市电光伏开关,
                _.控制柜手动开关,
            };
        }
        /// <summary>
        /// 获取值信息
        /// </summary>
        public override object[] GetValues()
        {
            return new object[] {
                this._TimeStamp,
                this._设定温度,
                this._水泵频率P,
                this._水泵频率I,
                this._水泵频率D,
                this._进水电磁阀开关,
                this._出水电磁阀开关,
                this._市电光伏开关,
                this._控制柜手动开关,
            };
        }
        /// <summary>
        /// 是否是v1.10.5.6及以上版本实体。
        /// </summary>
        /// <returns></returns>
        /// public override bool V1_10_5_6_Plus()
        /// {
        ///     return true;
        /// }
        #endregion

        #region _Field
        /// <summary>
        /// 字段信息
        /// </summary>
        public class _
        {
            /// <summary>
            /// * 
            /// </summary>
            public readonly static Field All = new Field("*", "系统采集器参数");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field TimeStamp = new Field("TimeStamp", "系统采集器参数", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field 设定温度 = new Field("设定温度", "系统采集器参数", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field 水泵频率P = new Field("水泵频率P", "系统采集器参数", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field 水泵频率I = new Field("水泵频率I", "系统采集器参数", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field 水泵频率D = new Field("水泵频率D", "系统采集器参数", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field 进水电磁阀开关 = new Field("进水电磁阀开关", "系统采集器参数", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field 出水电磁阀开关 = new Field("出水电磁阀开关", "系统采集器参数", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field 市电光伏开关 = new Field("市电光伏开关", "系统采集器参数", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field 控制柜手动开关 = new Field("控制柜手动开关", "系统采集器参数", "");
        }
        #endregion
    }
}

