//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dos.ORM;

namespace SolarhotwaterprojectModel
{
    /// <summary>
    /// 实体类系统采集器实时。(属性说明自动提取数据库字段的描述信息)
    /// </summary>
    [Table("系统采集器实时")]
    [Serializable]
    public partial class 系统采集器实时 : Entity
    {
        #region Model
        private DateTime? _TimeStamp;
        private string _环境温度;
        private string _太阳能辐照度;
        private string _风速;
        private string _湿度;
        private string _光伏输出直流电压;
        private string _光伏输出直流电流;
        private string _光伏输出直流功率;
        private string _光伏输出电能;
        private string _压缩机ab电压;
        private string _压缩机bc电压;
        private string _压缩机ca电压;
        private string _压缩机a相电流;
        private string _压缩机b相电流;
        private string _压缩机c相电流;
        private string _压缩机视在功率;
        private string _压缩机有功功率;
        private string _压缩机无功功率;
        private string _压缩机功率因素;
        private string _压缩机电能;
        private string _a相畸变电压;
        private string _a相畸变电流;
        private string _a相电压不平衡度;
        private string _a相电流不平衡度;
        private string _压缩机排气压力;
        private string _蒸发器出口压力;
        private string _压缩机排气温度;
        private string _冷凝器出口温度;
        private string _蒸发器出口温度;
        private string _蒸发器入口温度;
        private string _水泵变频运行电压;
        private string _水泵变频运行电流;
        private string _水泵变频运行功率;
        private string _水泵变频运行频率;
        private string _水泵电能;
        private string _供冷冷水质量流量;
        private string _冰块温度;
        private string _水箱上层水温;
        private string _供冷循环中回水温度;
        private string _水箱下层水温;
        private string _供冷循环中供水温度;
        private string _风机盘管出风口温度;
        private string _房间温度;
        private string _溢水量;
        private string _水箱液位;
        private string _逆控率;
        private string _能效比;
        private string _PID占空比;
        private string _太阳o光伏;
        private string _总电能;
        private string _压缩机频率;

        /// <summary>
        /// 
        /// </summary>
        [Field("TimeStamp")]
        public DateTime? TimeStamp
        {
            get { return _TimeStamp; }
            set
            {
                this.OnPropertyValueChange("TimeStamp");
                this._TimeStamp = value;
            }
        }

        private void OnPropertyValueChange(string v)
        {
            throw new NotImplementedException();
        }

        /// <summary>
        /// 
        /// </summary>
        [Field("环境温度")]
        public string 环境温度
        {
            get { return _环境温度; }
            set
            {
                this.OnPropertyValueChange("环境温度");
                this._环境温度 = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("太阳能辐照度")]
        public string 太阳能辐照度
        {
            get { return _太阳能辐照度; }
            set
            {
                this.OnPropertyValueChange("太阳能辐照度");
                this._太阳能辐照度 = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("风速")]
        public string 风速
        {
            get { return _风速; }
            set
            {
                this.OnPropertyValueChange("风速");
                this._风速 = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("湿度")]
        public string 湿度
        {
            get { return _湿度; }
            set
            {
                this.OnPropertyValueChange("湿度");
                this._湿度 = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("光伏输出直流电压")]
        public string 光伏输出直流电压
        {
            get { return _光伏输出直流电压; }
            set
            {
                this.OnPropertyValueChange("光伏输出直流电压");
                this._光伏输出直流电压 = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("光伏输出直流电流")]
        public string 光伏输出直流电流
        {
            get { return _光伏输出直流电流; }
            set
            {
                this.OnPropertyValueChange("光伏输出直流电流");
                this._光伏输出直流电流 = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("光伏输出直流功率")]
        public string 光伏输出直流功率
        {
            get { return _光伏输出直流功率; }
            set
            {
                this.OnPropertyValueChange("光伏输出直流功率");
                this._光伏输出直流功率 = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("光伏输出电能")]
        public string 光伏输出电能
        {
            get { return _光伏输出电能; }
            set
            {
                this.OnPropertyValueChange("光伏输出电能");
                this._光伏输出电能 = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("压缩机ab电压")]
        public string 压缩机ab电压
        {
            get { return _压缩机ab电压; }
            set
            {
                this.OnPropertyValueChange("压缩机ab电压");
                this._压缩机ab电压 = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("压缩机bc电压")]
        public string 压缩机bc电压
        {
            get { return _压缩机bc电压; }
            set
            {
                this.OnPropertyValueChange("压缩机bc电压");
                this._压缩机bc电压 = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("压缩机ca电压")]
        public string 压缩机ca电压
        {
            get { return _压缩机ca电压; }
            set
            {
                this.OnPropertyValueChange("压缩机ca电压");
                this._压缩机ca电压 = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("压缩机a相电流")]
        public string 压缩机a相电流
        {
            get { return _压缩机a相电流; }
            set
            {
                this.OnPropertyValueChange("压缩机a相电流");
                this._压缩机a相电流 = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("压缩机b相电流")]
        public string 压缩机b相电流
        {
            get { return _压缩机b相电流; }
            set
            {
                this.OnPropertyValueChange("压缩机b相电流");
                this._压缩机b相电流 = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("压缩机c相电流")]
        public string 压缩机c相电流
        {
            get { return _压缩机c相电流; }
            set
            {
                this.OnPropertyValueChange("压缩机c相电流");
                this._压缩机c相电流 = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("压缩机视在功率")]
        public string 压缩机视在功率
        {
            get { return _压缩机视在功率; }
            set
            {
                this.OnPropertyValueChange("压缩机视在功率");
                this._压缩机视在功率 = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("压缩机有功功率")]
        public string 压缩机有功功率
        {
            get { return _压缩机有功功率; }
            set
            {
                this.OnPropertyValueChange("压缩机有功功率");
                this._压缩机有功功率 = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("压缩机无功功率")]
        public string 压缩机无功功率
        {
            get { return _压缩机无功功率; }
            set
            {
                this.OnPropertyValueChange("压缩机无功功率");
                this._压缩机无功功率 = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("压缩机功率因素")]
        public string 压缩机功率因素
        {
            get { return _压缩机功率因素; }
            set
            {
                this.OnPropertyValueChange("压缩机功率因素");
                this._压缩机功率因素 = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("压缩机电能")]
        public string 压缩机电能
        {
            get { return _压缩机电能; }
            set
            {
                this.OnPropertyValueChange("压缩机电能");
                this._压缩机电能 = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("a相畸变电压")]
        public string a相畸变电压
        {
            get { return _a相畸变电压; }
            set
            {
                this.OnPropertyValueChange("a相畸变电压");
                this._a相畸变电压 = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("a相畸变电流")]
        public string a相畸变电流
        {
            get { return _a相畸变电流; }
            set
            {
                this.OnPropertyValueChange("a相畸变电流");
                this._a相畸变电流 = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("a相电压不平衡度")]
        public string a相电压不平衡度
        {
            get { return _a相电压不平衡度; }
            set
            {
                this.OnPropertyValueChange("a相电压不平衡度");
                this._a相电压不平衡度 = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("a相电流不平衡度")]
        public string a相电流不平衡度
        {
            get { return _a相电流不平衡度; }
            set
            {
                this.OnPropertyValueChange("a相电流不平衡度");
                this._a相电流不平衡度 = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("压缩机排气压力")]
        public string 压缩机排气压力
        {
            get { return _压缩机排气压力; }
            set
            {
                this.OnPropertyValueChange("压缩机排气压力");
                this._压缩机排气压力 = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("蒸发器出口压力")]
        public string 蒸发器出口压力
        {
            get { return _蒸发器出口压力; }
            set
            {
                this.OnPropertyValueChange("蒸发器出口压力");
                this._蒸发器出口压力 = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("压缩机排气温度")]
        public string 压缩机排气温度
        {
            get { return _压缩机排气温度; }
            set
            {
                this.OnPropertyValueChange("压缩机排气温度");
                this._压缩机排气温度 = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("冷凝器出口温度")]
        public string 冷凝器出口温度
        {
            get { return _冷凝器出口温度; }
            set
            {
                this.OnPropertyValueChange("冷凝器出口温度");
                this._冷凝器出口温度 = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("蒸发器出口温度")]
        public string 蒸发器出口温度
        {
            get { return _蒸发器出口温度; }
            set
            {
                this.OnPropertyValueChange("蒸发器出口温度");
                this._蒸发器出口温度 = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("蒸发器入口温度")]
        public string 蒸发器入口温度
        {
            get { return _蒸发器入口温度; }
            set
            {
                this.OnPropertyValueChange("蒸发器入口温度");
                this._蒸发器入口温度 = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("水泵变频运行电压")]
        public string 水泵变频运行电压
        {
            get { return _水泵变频运行电压; }
            set
            {
                this.OnPropertyValueChange("水泵变频运行电压");
                this._水泵变频运行电压 = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("水泵变频运行电流")]
        public string 水泵变频运行电流
        {
            get { return _水泵变频运行电流; }
            set
            {
                this.OnPropertyValueChange("水泵变频运行电流");
                this._水泵变频运行电流 = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("水泵变频运行功率")]
        public string 水泵变频运行功率
        {
            get { return _水泵变频运行功率; }
            set
            {
                this.OnPropertyValueChange("水泵变频运行功率");
                this._水泵变频运行功率 = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("水泵变频运行频率")]
        public string 水泵变频运行频率
        {
            get { return _水泵变频运行频率; }
            set
            {
                this.OnPropertyValueChange("水泵变频运行频率");
                this._水泵变频运行频率 = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("水泵电能")]
        public string 水泵电能
        {
            get { return _水泵电能; }
            set
            {
                this.OnPropertyValueChange("水泵电能");
                this._水泵电能 = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("供冷冷水质量流量")]
        public string 供冷冷水质量流量
        {
            get { return _供冷冷水质量流量; }
            set
            {
                this.OnPropertyValueChange("供冷冷水质量流量");
                this._供冷冷水质量流量 = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("冰块温度")]
        public string 冰块温度
        {
            get { return _冰块温度; }
            set
            {
                this.OnPropertyValueChange("冰块温度");
                this._冰块温度 = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("水箱上层水温")]
        public string 水箱上层水温
        {
            get { return _水箱上层水温; }
            set
            {
                this.OnPropertyValueChange("水箱上层水温");
                this._水箱上层水温 = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("供冷循环中回水温度")]
        public string 供冷循环中回水温度
        {
            get { return _供冷循环中回水温度; }
            set
            {
                this.OnPropertyValueChange("供冷循环中回水温度");
                this._供冷循环中回水温度 = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("水箱下层水温")]
        public string 水箱下层水温
        {
            get { return _水箱下层水温; }
            set
            {
                this.OnPropertyValueChange("水箱下层水温");
                this._水箱下层水温 = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("供冷循环中供水温度")]
        public string 供冷循环中供水温度
        {
            get { return _供冷循环中供水温度; }
            set
            {
                this.OnPropertyValueChange("供冷循环中供水温度");
                this._供冷循环中供水温度 = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("风机盘管出风口温度")]
        public string 风机盘管出风口温度
        {
            get { return _风机盘管出风口温度; }
            set
            {
                this.OnPropertyValueChange("风机盘管出风口温度");
                this._风机盘管出风口温度 = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("房间温度")]
        public string 房间温度
        {
            get { return _房间温度; }
            set
            {
                this.OnPropertyValueChange("房间温度");
                this._房间温度 = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("溢水量")]
        public string 溢水量
        {
            get { return _溢水量; }
            set
            {
                this.OnPropertyValueChange("溢水量");
                this._溢水量 = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("水箱液位")]
        public string 水箱液位
        {
            get { return _水箱液位; }
            set
            {
                this.OnPropertyValueChange("水箱液位");
                this._水箱液位 = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("逆控率")]
        public string 逆控率
        {
            get { return _逆控率; }
            set
            {
                this.OnPropertyValueChange("逆控率");
                this._逆控率 = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("能效比")]
        public string 能效比
        {
            get { return _能效比; }
            set
            {
                this.OnPropertyValueChange("能效比");
                this._能效比 = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("PID占空比")]
        public string PID占空比
        {
            get { return _PID占空比; }
            set
            {
                this.OnPropertyValueChange("PID占空比");
                this._PID占空比 = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("太阳o光伏")]
        public string 太阳o光伏
        {
            get { return _太阳o光伏; }
            set
            {
                this.OnPropertyValueChange("太阳o光伏");
                this._太阳o光伏 = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("总电能")]
        public string 总电能
        {
            get { return _总电能; }
            set
            {
                this.OnPropertyValueChange("总电能");
                this._总电能 = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("压缩机频率")]
        public string 压缩机频率
        {
            get { return _压缩机频率; }
            set
            {
                this.OnPropertyValueChange("压缩机频率");
                this._压缩机频率 = value;
            }
        }
        #endregion

        #region Method
        /// <summary>
        /// 获取实体中的主键列
        /// </summary>
        public override Field[] GetPrimaryKeyFields()
        {
            return new Field[] {
            };
        }
        /// <summary>
        /// 获取列信息
        /// </summary>
        public override Field[] GetFields()
        {
            return new Field[] {
                _.TimeStamp,
                _.环境温度,
                _.太阳能辐照度,
                _.风速,
                _.湿度,
                _.光伏输出直流电压,
                _.光伏输出直流电流,
                _.光伏输出直流功率,
                _.光伏输出电能,
                _.压缩机ab电压,
                _.压缩机bc电压,
                _.压缩机ca电压,
                _.压缩机a相电流,
                _.压缩机b相电流,
                _.压缩机c相电流,
                _.压缩机视在功率,
                _.压缩机有功功率,
                _.压缩机无功功率,
                _.压缩机功率因素,
                _.压缩机电能,
                _.a相畸变电压,
                _.a相畸变电流,
                _.a相电压不平衡度,
                _.a相电流不平衡度,
                _.压缩机排气压力,
                _.蒸发器出口压力,
                _.压缩机排气温度,
                _.冷凝器出口温度,
                _.蒸发器出口温度,
                _.蒸发器入口温度,
                _.水泵变频运行电压,
                _.水泵变频运行电流,
                _.水泵变频运行功率,
                _.水泵变频运行频率,
                _.水泵电能,
                _.供冷冷水质量流量,
                _.冰块温度,
                _.水箱上层水温,
                _.供冷循环中回水温度,
                _.水箱下层水温,
                _.供冷循环中供水温度,
                _.风机盘管出风口温度,
                _.房间温度,
                _.溢水量,
                _.水箱液位,
                _.逆控率,
                _.能效比,
                _.PID占空比,
                _.太阳o光伏,
                _.总电能,
                _.压缩机频率,
            };
        }
        /// <summary>
        /// 获取值信息
        /// </summary>
        public override object[] GetValues()
        {
            return new object[] {
                this._TimeStamp,
                this._环境温度,
                this._太阳能辐照度,
                this._风速,
                this._湿度,
                this._光伏输出直流电压,
                this._光伏输出直流电流,
                this._光伏输出直流功率,
                this._光伏输出电能,
                this._压缩机ab电压,
                this._压缩机bc电压,
                this._压缩机ca电压,
                this._压缩机a相电流,
                this._压缩机b相电流,
                this._压缩机c相电流,
                this._压缩机视在功率,
                this._压缩机有功功率,
                this._压缩机无功功率,
                this._压缩机功率因素,
                this._压缩机电能,
                this._a相畸变电压,
                this._a相畸变电流,
                this._a相电压不平衡度,
                this._a相电流不平衡度,
                this._压缩机排气压力,
                this._蒸发器出口压力,
                this._压缩机排气温度,
                this._冷凝器出口温度,
                this._蒸发器出口温度,
                this._蒸发器入口温度,
                this._水泵变频运行电压,
                this._水泵变频运行电流,
                this._水泵变频运行功率,
                this._水泵变频运行频率,
                this._水泵电能,
                this._供冷冷水质量流量,
                this._冰块温度,
                this._水箱上层水温,
                this._供冷循环中回水温度,
                this._水箱下层水温,
                this._供冷循环中供水温度,
                this._风机盘管出风口温度,
                this._房间温度,
                this._溢水量,
                this._水箱液位,
                this._逆控率,
                this._能效比,
                this._PID占空比,
                this._太阳o光伏,
                this._总电能,
                this._压缩机频率,
            };
        }
        /// <summary>
        /// 是否是v1.10.5.6及以上版本实体。
        /// </summary>
        /// <returns></returns>
        //public override bool V1_10_5_6_Plus()
        //{
        //    return true;
       // }
        #endregion

        #region _Field
        /// <summary>
        /// 字段信息
        /// </summary>
        public class _
        {
            /// <summary>
            /// * 
            /// </summary>
            public readonly static Field All = new Field("*", "系统采集器实时");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field TimeStamp = new Field("TimeStamp", "系统采集器实时", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field 环境温度 = new Field("环境温度", "系统采集器实时", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field 太阳能辐照度 = new Field("太阳能辐照度", "系统采集器实时", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field 风速 = new Field("风速", "系统采集器实时", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field 湿度 = new Field("湿度", "系统采集器实时", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field 光伏输出直流电压 = new Field("光伏输出直流电压", "系统采集器实时", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field 光伏输出直流电流 = new Field("光伏输出直流电流", "系统采集器实时", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field 光伏输出直流功率 = new Field("光伏输出直流功率", "系统采集器实时", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field 光伏输出电能 = new Field("光伏输出电能", "系统采集器实时", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field 压缩机ab电压 = new Field("压缩机ab电压", "系统采集器实时", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field 压缩机bc电压 = new Field("压缩机bc电压", "系统采集器实时", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field 压缩机ca电压 = new Field("压缩机ca电压", "系统采集器实时", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field 压缩机a相电流 = new Field("压缩机a相电流", "系统采集器实时", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field 压缩机b相电流 = new Field("压缩机b相电流", "系统采集器实时", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field 压缩机c相电流 = new Field("压缩机c相电流", "系统采集器实时", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field 压缩机视在功率 = new Field("压缩机视在功率", "系统采集器实时", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field 压缩机有功功率 = new Field("压缩机有功功率", "系统采集器实时", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field 压缩机无功功率 = new Field("压缩机无功功率", "系统采集器实时", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field 压缩机功率因素 = new Field("压缩机功率因素", "系统采集器实时", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field 压缩机电能 = new Field("压缩机电能", "系统采集器实时", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field a相畸变电压 = new Field("a相畸变电压", "系统采集器实时", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field a相畸变电流 = new Field("a相畸变电流", "系统采集器实时", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field a相电压不平衡度 = new Field("a相电压不平衡度", "系统采集器实时", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field a相电流不平衡度 = new Field("a相电流不平衡度", "系统采集器实时", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field 压缩机排气压力 = new Field("压缩机排气压力", "系统采集器实时", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field 蒸发器出口压力 = new Field("蒸发器出口压力", "系统采集器实时", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field 压缩机排气温度 = new Field("压缩机排气温度", "系统采集器实时", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field 冷凝器出口温度 = new Field("冷凝器出口温度", "系统采集器实时", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field 蒸发器出口温度 = new Field("蒸发器出口温度", "系统采集器实时", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field 蒸发器入口温度 = new Field("蒸发器入口温度", "系统采集器实时", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field 水泵变频运行电压 = new Field("水泵变频运行电压", "系统采集器实时", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field 水泵变频运行电流 = new Field("水泵变频运行电流", "系统采集器实时", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field 水泵变频运行功率 = new Field("水泵变频运行功率", "系统采集器实时", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field 水泵变频运行频率 = new Field("水泵变频运行频率", "系统采集器实时", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field 水泵电能 = new Field("水泵电能", "系统采集器实时", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field 供冷冷水质量流量 = new Field("供冷冷水质量流量", "系统采集器实时", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field 冰块温度 = new Field("冰块温度", "系统采集器实时", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field 水箱上层水温 = new Field("水箱上层水温", "系统采集器实时", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field 供冷循环中回水温度 = new Field("供冷循环中回水温度", "系统采集器实时", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field 水箱下层水温 = new Field("水箱下层水温", "系统采集器实时", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field 供冷循环中供水温度 = new Field("供冷循环中供水温度", "系统采集器实时", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field 风机盘管出风口温度 = new Field("风机盘管出风口温度", "系统采集器实时", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field 房间温度 = new Field("房间温度", "系统采集器实时", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field 溢水量 = new Field("溢水量", "系统采集器实时", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field 水箱液位 = new Field("水箱液位", "系统采集器实时", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field 逆控率 = new Field("逆控率", "系统采集器实时", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field 能效比 = new Field("能效比", "系统采集器实时", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field PID占空比 = new Field("PID占空比", "系统采集器实时", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field 太阳o光伏 = new Field("太阳o光伏", "系统采集器实时", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field 总电能 = new Field("总电能", "系统采集器实时", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field 压缩机频率 = new Field("压缩机频率", "系统采集器实时", "");
        }
        #endregion
    }
}